services:
  api:
    build: .
    container_name: admin_api
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/admin_db
      - SECRET_KEY=dev-secret
      - JWT_SECRET_KEY=dev-jwt
      - CORS_ORIGINS=*
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: admin_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=admin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ../admin-fronted
    container_name: admin_frontend
    depends_on:
      - api
    ports:
      - "8080:80"      # Acceso al frontend en http://localhost:8080
    # Si quieres parametrizar el build con otra base de API:
    environment:
      - VITE_API_BASE=/api/v1
volumes:
  pgdata:
